export const AZURE_OPENAI_ENDPOINT = "";
export const AZURE_OPENAI_KEY = "";
export const AZURE_OPENAI_DEPLOYMENT = "";
export const AZURE_STORAGE_CONNECTION_STRING = "";

export const env = {
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_STORAGE_CONNECTION_STRING,
};
